### PR TITLE
small changes, use commands to change dashboard values

### PR DESCRIPTION
**Pull request by MichaelDvP**
Check if you like it, this is my preference.
one very small issue i've foundwhile testing, don't know how to fix: 
When open the dashboard the existing devices are expanded, but new detected devices are added collapsed. Button is still set to expand.

### CODE REVIEW

**Comment by proddy** [comment]
Thanks. The table tree is tricky - you can't explicitly set the expand/contract, only toggle it. I did a bit of a hack, but I think I'll see if I can do a PR on the maintainer's code or ask him if there is a better method. 

The USB Serial not working, i still don't understand the bug. What would removing "-DBOARD_HAS_PSRAM" change anything? BTW I know this flag is automatically added by PIO but I had purposely left it in there to remind people it does support PSRAM. I don't always trust those PIO board configs.

**Comment by MichaelDvP** [comment]
Look at the board file https://github.com/platformio/platform-espressif32/blob/master/boards/lolin_s3.json
the extra flags -DARDUINO_USB_CDC_ON_BOOT=1 and -DARDUINO_USB_MODE=1 controls the USB serial, but setting extra flags in pio.ini overwrites it. Thelolin-s3- board has ps-ram already set. For esp32dev this is no issue: https://github.com/platformio/platform-espressif32/blob/master/boards/esp32dev.json but we need to set  PS-RAM for the E32V2 gateway.

BTW: another very small issue: there is always a scrollbar in the (expanded) box, scrolling only 1px up and down. longer lists grows the box and the window gets a real scrollbar. The inner one is not needed.

**Comment by proddy** [comment]
Ah, of course, setting the `extra_flags` overwrites all of the previous default ones. Should have known, good spot!

**Comment by proddy** [comment]
@MichaelDvP think I fixed in 1-pixel inner scrollbar. It was caused by the view expanding because of the on hover borders, so I had to make some changes, but as a cost. let me know what you think. 

Also, do you think the row show's be selectable? i.e. click to edit (if available)?

**Pull request merged**
